version: '3.8'
name: auth

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: auth-postgres
    volumes:
      - ./postgres_data:/bitnami/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    command: 
      - start-dev
    networks:
      - keycloak-net

networks:
  keycloak-net:
    name: keycloak-net
    driver: bridge
